import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Il nome del tuo sito",
    description: "Descrizione generale del tuo sito",
    url: "https://tuo-sito.com",
    siteName: "Nome del sito",
    images: [
      {
        url: "https://tuo-sito.com/immagine-di-anteprima.jpg",
        width: 1200,
        height: 630,
      },
    ],
    locale: "it_IT",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 text-zinc-100`}>
          <p className="bg-purple-700 text-white w-full text-center py-2 ">
            Sono al layaout root
          </p>
          <Navbar/>
        {children}
      </body>
    </html>
  );
}
